version: "3"
services:
    node:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        environment:
            - ENABLE_GATSBY_REFRESH_ENDPOINT=true
        command: gatsby develop -H 0.0.0.0
